# Generated by Django 4.1.1 on 2022-09-29 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('idalumno', models.BigAutoField(primary_key=True, serialize=False)),
                ('matricula', models.CharField(blank=True, max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('apellidoP', models.CharField(max_length=100)),
                ('apellidoM', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
                ('convenio', models.CharField(max_length=800)),
                ('inicioCurso', models.DateField()),
                ('finalCurso', models.DateField()),
                ('observaciones', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('iddireccion', models.BigAutoField(primary_key=True, serialize=False)),
                ('calle', models.CharField(max_length=100)),
                ('lote', models.IntegerField()),
                ('manzana', models.IntegerField()),
                ('colonia', models.CharField(max_length=100)),
                ('delegacionMunicipio', models.CharField(max_length=100)),
                ('codigopostal', models.IntegerField()),
                ('ciudadOestado', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Escuela',
            fields=[
                ('idescuela', models.BigAutoField(primary_key=True, serialize=False)),
                ('plantel', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('idtutor', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellidoP', models.CharField(max_length=100)),
                ('apellidoM', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idusuario', models.BigAutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('tipo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('idpago', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipoPago', models.CharField(max_length=100)),
                ('mesPagado', models.CharField(max_length=12)),
                ('idalumno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories7', to='Cedva1.alumno')),
            ],
        ),
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('idespecialidad', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('idescuela', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories8', to='Cedva1.escuela')),
            ],
        ),
        migrations.AddField(
            model_name='alumno',
            name='iddireccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories2', to='Cedva1.direccion'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='idescuela',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='Cedva1.escuela'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='idespecialidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories1', to='Cedva1.especialidad'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='idtutor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories3', to='Cedva1.tutor'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='idusuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories4', to='Cedva1.usuario'),
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('idadministrador', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellidoP', models.CharField(max_length=100)),
                ('apellidoM', models.CharField(max_length=100)),
                ('idescuela', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories5', to='Cedva1.escuela')),
                ('idusuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories6', to='Cedva1.usuario')),
            ],
        ),
    ]
